spring:
  aop:
    auto: true
  freemarker:
    charset: utf-8
    content-type: text/html
    allow-request-override: false
    cache: true
    check-template-location: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl
server:
  port: 8081
  servlet:
    context-path: /helloworld

